### ISSUE TITLE
Refine responsive CSS for small window sizes

### ISSUE THREAD

**Issue by jwasilgeo** [thollingshead/lets-chat#2]
I have a habit of keeping a chat client up in a separate browser window and keeping a pretty small browser window size.  As an enhancement request--that I'd be glad to work on--I propose altering some of the CSS for these kinds of use cases.  The landing page / room list seems fine, but I think the in-room page might need some tweaking.
- Fix: at ~992px width and smaller, messages are cut off horizontally in `<div class="lcb-room-chat">` when the `<div class="lcb-room-sidebar">` panel is open.
- Change: at 767px width (appears to be the bootstrap number value), the left-hand room menu disappears and goes into :hamburger: menu mode.  I like it, but I propose making this occur earlier, maybe at 850px width.  The header also appears and is 43px high; this could be shorter when the browser window size has a small height, say 350px.

Any and all, please chime in with your opinions.  High-5.

**Comment by thollingsheadesri** [comment]
@jwasil Is this something that could/should be addressed upstream?

**Comment by jwasil** [comment]
@thollingsheadesri maybe the fix item, yeah. I'll review the contrib guidelines and maybe put something in there.  Good point!
